### PR TITLE
Quote font names to fix font names with (space)(digits) at the end not working

### PR DESCRIPTION
**Pull request by rpkamp**

### CODE REVIEW

**Comment by oleedd** [comment]
Also this works `"'" + font`. Just to let you know.

**Comment by rpkamp** [comment]
I know, it's the same solution, but a different syntax. I'm using [ES6 template literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals).

**Comment by oleedd** [comment]
I think it is not easy to transform in ES5.

**Comment by rpkamp** [comment]
It's already doing that using webpack. Been doing it for years.

**Comment by oleedd** [comment]
No, quite easy. Now I see it just uses `concat` instead but ES6 is much shorter.

**Pull request merged**
