### PR TITLE
Add bookmarklet support

### PR DESCRIPTION
**Pull request by JLChnToZ**
As the title wrotes.

### CODE REVIEW

**Comment by rpkamp** [comment]
Thanks! I'll have a stab at the merge conflicts later.

**Comment by JLChnToZ** [comment]
I helped a bit to resolve conflicts (include moving the changes), hope this does not violate the new project structure.

**Comment by rpkamp** [comment]
It probably will, since I'm in the middle of moving everything over from plain javascript to typescript.

I'll incorporate your changes once that's done.

**Comment by rpkamp** [comment]
I've copies the relevant parts over to a new PR: https://github.com/rpkamp/chrome-minimal-bookmarks-tree/pull/136

Also, I've made the permissions for `http://`, `https://`, and `file://` optional, so that people who don't use bookmarklets don't have to grant those permissions.

I'll close this PR now. Thanks for this though!

**Pull request closed without merging**
