### PR TITLE
Overhaul to 5.0

### PR DESCRIPTION
**Pull request by rpkamp**
Switch to TypeScript and refactor until it becomes more readable again :slightly_smiling_face: 

TO DO:

- [x] Introduce a `BookmarkOpener` - this is done all over the place and should be centralised
- [x] Replace `addClass`, `removeClass`, `hasClass` etc with `classList` - note that if we use `.classList.replace()` then the min required version for chrome must be bumped to 61
- [x] Use less `document.querySelector` - it requires loads of boilerplate
- [x] Set "strict" and "strictNullChecks" TS compilerOptions to true
- [x] Add missing translations to `nl` and `de`
- [x] Add `Makefile` command to download translations
- [x] Clean up settings so it no longer returns `string | number | boolean | null` - that's just messy
- [x] Overhaul `ContextMenu` to `ContextMenuRenderer` and add tests
- [x] Introduce a class for building the tree
- [x] Update testing section in README
- [x] Run some final tests to check that everything still works as it should

### CODE REVIEW

**Comment by rpkamp** [comment]
What should still be done:

- [ ] Introduce a `BookmarkOpener` - this is done all over the place and should be centralised
- [ ] Replace `addClass`, `removeClass`, `hasClass` etc with `classList` - note that if we use `.classList.replace()` then the min required version for chrome must be bumped to 61
- [ ] Introduce a class for building the tree
- [ ] Use less `document.querySelector` - it requires loads of boilerplate
- [ ] Set "strict" and "strictNullChecks" TS compilerOptions to true
- [ ] Clean up settings so it no longer returns `string | number | boolean | null` - that's just messy

**Comment by oleedd** [comment]
Why minimum Chrome version 70 (it was 51 before)?

**Comment by rpkamp** [comment]
Because 51 is ancient and people should not use it anymore

**Comment by oleedd** [comment]
But I use 65.

**Comment by oleedd** [comment]
Why did you convert ES6 to ES5 all this long time if Chrome supports ES6 from v.51 (but you blocked all the previous versions without ES6)? Useless work and increasing code size.
The Chrome version string should be objective but not forcing to update.
I use 65 and can't update the extension. Can you change 70 to 65?

**Comment by rpkamp** [comment]
Why do you use chrome 65? It's from March 2018 and Google itself doesn't support it anymore. Why should I?

Actually, give [the list of CVE's against chrome](https://www.cvedetails.com/vulnerability-list.php?vendor_id=1224&product_id=15031&version_id=&page=1&hasexp=0&opdos=0&opec=0&opov=0&opcsrf=0&opgpriv=0&opsqli=0&opxss=0&opdirt=0&opmemc=0&ophttprs=0&opbyp=0&opfileinc=0&opginf=0&cvssscoremin=9&cvssscoremax=0&year=0&month=0&cweid=0&order=1&trc=214&sha=87d66415f750eb183c8c7800b4bfdd3d5d8d33a7) I should probably bump support to version 73, instead of lowering it and allowing people to use while being vulnerable to even more CVE's.

this is fine/cdn.vox-cdn.com/uploads/chorus_image/image/49493993/this-is-fine.0.jpg)

**Comment by oleedd** [comment]
Because most other extension are without limits and don't use that string. And it is absurd to use it if you don't use some new javascript features. The rational way is to delete that string.
I like trapezoid tabs and the previous Chrome look but can't find a hack for this:
image
Just imagine how many vulnerabilities are not found by Google yet but hackers know them.

**Comment by rpkamp** [comment]
> Just imagine how many vulnerabilities are not found by Google yet but hackers know them.

So? That's not an excuse to continue to use a product with _known_ and _documented_ vulnerabilities.

I'm not doing it.

**Comment by oleedd** [comment]
Why do you limit users? Do you work for Google? Only they are interested to update Chrome for all users. Users should decide what version to use but not you.
You just lose some part of users and donation. If people see that it is not supported - will they figure out why and try to fix this or just install another extension without limits.

**Comment by rpkamp** [comment]
Asked and answered.

**Comment by oleedd** [comment]
I planned to fix bugs, code new features and keep reporting new bugs and ideas. But now I should use the previous version because it is too hard for you to decrease the number by 5 digits.

**Comment by oleedd** [comment]
I planned to fix bugs, code new features and keep reporting new bugs and ideas. But now I should use the previous version because it is too hard for you to decrease the number by 5 digits. Thanks.

**Comment by oleedd** [comment]
Not a problem - I can hack manifest.

**Pull request merged**
