### PR TITLE
Initialise omnibox on extension install as well

### PR DESCRIPTION
**Pull request by rpkamp**

### CODE REVIEW

**Comment by MartinLichtblau** [comment]
#bug Omnibox search does not work anymore.

**Comment by rpkamp** [comment]
Have you tried restarting chrome?

**Comment by MartinLichtblau** [comment]
Yes, tried restarting chrome and tried uninstall extension.

**Comment by rpkamp** [comment]
Which version of the extension are you running? 4.5.1? Also, which OS and which Chrome version?

**Comment by MartinLichtblau** [comment]
Google Chrome is Version 65.0.3325.162 (Official Build) (64-bit)
BMT Version 4.5.1

**Comment by MartinLichtblau** [comment]
Update:
It works, for normal bookmarks. When I remove and install it anew the search works fine. When I open a single page it also works fine afterwards.
The issue only exists when you open a bookmarks folder! After you opened a folder the search doesn't work anymore; it is stuck and always only shows the last opened folder.

**Comment by rpkamp** [comment]
This is fixed in the latest release (v4.5.2).

Thanks for the report @MartinLichtblau !

**Pull request merged**
